version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
